In [44]:
import random
import pandas as pd
wassup_3 = [ 
 '고민혁',
 '김송원',
 '김수민',
 '김예인',
 '김준호',
 '김하나',
 '박선정',
 '이지안',
 '전영권',
 '정일상',
 '채영호',
 '최효진']
random.seed(240618) # randomstate 무작위숫자
random.shuffle(wassup_3)

# 몇조까지, 몇명까지
teams = 4
team_num = 3

dedenzzi = pd.DataFrame(columns=[f'{i+1}조' for i in range(teams)], index=range(team_num))

# n명씩 무작위 배치
for i in range(len(dedenzzi.columns)):
    for j in range(team_num):
        if wassup_3:
            dedenzzi.iloc[j,i] = wassup_3.pop()
        else:
            break

# 남은인원 순서대로 추가배치
while wassup_3:
    for col in dedenzzi.columns:
        if not wassup_3:
            break
        dedenzzi.loc[team_num, col] = wassup_3.pop()

# 팀원 이름순 정렬
for col in dedenzzi.columns:
    dedenzzi[col] = dedenzzi[col].sort_values().reset_index(drop=True)
dedenzzi

    1조   2조   3조   4조
0  김예인  김수민  고민혁  김송원
1  정일상  박선정  김준호  이지안
2  최효진  채영호  김하나  전영권